[package]
name = "University-Game"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = {version = "4.8.0"}
tokio = {version = "1.38.0"}
rand = "0.9.0-alpha.1"
sqlx = {version = "0.7.4", features = ["runtime-tokio", "runtime-tokio-rustls"]}